### ISSUE TITLE
New metadata file not correctly associated with the EBSD (texture) experiment

### ISSUE THREAD

**Issue by aplowman** [LightForm-group/wiki#5]
@merrygoat has added a new metadata file named `ebsd-(texture).yml`, which should be automatically associated with the EBSD (texture) experiment, but it is not. For example, on the Experiments home page, there is a link to add the metadata file, when there should be a link to edit the metadata file:

![image](https://user-images.githubusercontent.com/5176471/58173081-4834cc80-7c92-11e9-8407-006a47c7d924.png)

**Comment by merrygoat** [comment]
I added it through the web interface using the add button but on the first attempt, was was not able to save my edited page due to not having authenticated the wiki addin to access my github. Once I had authenticated it I then added it successfully through the web interface.

**Comment by aplowman** [comment]
Thanks for the info @merrygoat. This was an issue with parentheses in the metadata file names. The authentication thing with Prose is a bit annoying but a separate issue. It's not particularly intuitive, but using Prose.io seem to be the best available solution at the moment. The worst that can happen if you don't authenticate is that instead of directly committing you end up submitting a pull request, which you then have to approve.

Fixed with 326386cf461ab966910f3fe9c2fdb79eb2e4bf20 and 9bf348450a4f1032bd72618ee459fca76f63a9ee.
